### ISSUE TITLE
Panic at the fields

### ISSUE THREAD

**Issue by nicorevin** [mheese/journalbeat#17]
I can't get all this `fields` stuff working at all now.
Without `fields` and `field_dest` everything goes smooth.

But when I add smth like:

```yaml
input:
  fields_dest: anything
  fields:
    lol: woot
```

I receive this:

```sh
$ sudo ./journalbeat
panic: reflect.Set: value of type common.MapStr is not assignable to type *common.MapStr

goroutine 1 [running]:
panic(0x8acd00, 0xc8201b3d20)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
reflect.Value.assignTo(0xa2cfe0, 0xc8201b8f30, 0x15, 0xa7da60, 0xb, 0xa2ac40, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:2164 +0x3be
reflect.Value.Set(0xa2ac40, 0xc8200930d8, 0x196, 0xa2cfe0, 0xc8201b8f30, 0x15)
        /usr/local/go/src/reflect/value.go:1334 +0x95
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyGetField(0xc8201b8ab0, 0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0x0, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:161 +0x252
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyStruct(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0xa1b7a0, 0xc820093040, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:122 +0xc22
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyMergeValue(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:298 +0x1026
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyGetField(0xc8201b8150, 0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0x0, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:156 +0x1aa
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyStruct(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x55d400, 0x98ebc0, 0xc8200a4a00, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:122 +0xc22
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyInto(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0xa61000, 0x98ebc0, 0xc8200a4a00, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:40 +0x319
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.(*Config).Unpack(0xc8201b8150, 0x87b240, 0xc8200a4a00, 0xc82014fc90, 0x1, 0x1, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:24 +0x356
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common.(*Config).Unpack(0xc8201b8150, 0x87b240, 0xc8200a4a00, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common/config.go:34 +0xc8
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/cfgfile.Read(0x87b240, 0xc8200a4a00, 0x0, 0x0, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/cfgfile/cfgfile.go:53 +0x88
github.com/mheese/journalbeat/beat.(*Journalbeat).Config(0xc8200a4a00, 0xc82005e900, 0x0, 0x0)
        github.com/mheese/journalbeat/beat/journalbeat.go:75 +0x98
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat.(*instance).config(0xc8200e53e0, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:238 +0x78d
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat.(*instance).launch(0xc8200e53e0, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:296 +0xa0
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat.Run(0xa7a3d0, 0xb, 0xa611e8, 0x5, 0x7f2df66f5c48, 0xc8200a4a00, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:126 +0x6d
main.main()
        github.com/mheese/journalbeat/main.go:26 +0x7d
```

**Comment by nicorevin** [comment]
so ok, `fields` and `fields_under_root` along with some other fields [are inherited](https://github.com/elastic/beats/blob/4125deafc73aab243519f5ae46d4d34072ba3c7c/libbeat/common/mapstr.go#L26) from `github.com/elastic/beats/libbeat/common`. So if you want to add some extra fields you should define them [on the top level of your config](https://github.com/elastic/beats/blob/1eab5b0b3e428e7d09c1521488f8972fca845f4a/libbeat/docs/shipperconfig.asciidoc). For instance:
```yaml
input: 
  # some input fields
output:
  # libbeat output 
fields:
  cluster_name: YourClusterName
  lol:
    woot: okok
fields_under_root: true
```
which will result in `cluster_name` and `lol.woot` fields appearing in your ELK.

I don't know whether the existing `fields` and `fields_dest` can be considered redundant though...

@alejojo, @slavikvin

**Comment by mheese** [comment]
sounds like they finally added that "fields" feature into libbeat (where it actually belongs IMO). @nicorevin  does it support nested fields as well? If not, it feels like we should make a PR against libbeat and remove the fields functionality from journalbeat.

**Comment by nicorevin** [comment]
Nested fields are in the example i've provided - `lol.woot` :)

**Comment by mheese** [comment]
seems to fix it ... closing this now
