### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by dwerder** [mheese/journalbeat#4]
@mheese thanks for the beat. We are testing your beat at the moment and found a possible "bug":

The error occurs, when we set the output to console and logstash to watch what is going on. If we just set one output everything seems to work fine.
Our config look like that:

```
shipper:
  name: journalbeat
input:
  write_cursor_state: true
  cursor_state_file: /tmp/journalbeat-cursor-state
  flush_cursor_secs: 3
  seek_to_cursor: true
  seek_to_head: false
  seek_to_tail: true
  clean_field_names: true
  convert_to_numbers: false
  move_metadata_to_field: journal
output:
  console:
    pretty: true
  logstash:
    hosts: ["logstash.test.domain:5044"]
```

The error message appears randomly after a few logs.

```
fatal error: concurrent map read and map write

goroutine 4 [running]:
runtime.throw(0xaa0500, 0x21)
    /root/go/src/runtime/panic.go:530 +0x90 fp=0xc8200475e0 sp=0xc8200475c8
runtime.mapaccessK(0x9db000, 0xc820076210, 0xc8200a6708, 0xa0b860, 0xc800000000)
    /root/go/src/runtime/hashmap.go:389 +0x5a fp=0xc820047628 sp=0xc8200475e0
runtime.mapiternext(0xc82055e900)
    /root/go/src/runtime/hashmap.go:774 +0x63e fp=0xc8200476b8 sp=0xc820047628
reflect.mapiternext(0xc82055e900)
    /root/go/src/runtime/hashmap.go:1020 +0x21 fp=0xc8200476c8 sp=0xc8200476b8
reflect.Value.MapKeys(0x9db000, 0xc820076210, 0x15, 0x0, 0x0, 0x0)
    /root/go/src/reflect/value.go:1095 +0x294 fp=0xc820047788 sp=0xc8200476c8
encoding/json.(*mapEncoder).encode(0xc82014c190, 0xc8203266e0, 0x9db000, 0xc820076210, 0x15, 0x0)
    /root/go/src/encoding/json/encode.go:614 +0xd6 fp=0xc820047878 sp=0xc820047788
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc8203266e0, 0x9db000, 0xc820076210, 0x15, 0xc820076200)
    /root/go/src/encoding/json/encode.go:632 +0x51 fp=0xc8200478b0 sp=0xc820047878
encoding/json.(*encodeState).reflectValue(0xc8203266e0, 0x9db000, 0xc820076210, 0x15)
    /root/go/src/encoding/json/encode.go:301 +0x6b fp=0xc8200478e0 sp=0xc8200478b0
encoding/json.(*encodeState).marshal(0xc8203266e0, 0x9db000, 0xc820076210, 0x0, 0x0)
    /root/go/src/encoding/json/encode.go:274 +0xa9 fp=0xc820047928 sp=0xc8200478e0
encoding/json.Marshal(0x9db000, 0xc820076210, 0x0, 0x0, 0x0, 0x0, 0x0)
    /root/go/src/encoding/json/encode.go:139 +0x84 fp=0xc820047960 sp=0xc820047928
encoding/json.MarshalIndent(0x9db000, 0xc820076210, 0x0, 0x0, 0xa0e908, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
    /root/go/src/encoding/json/encode.go:148 +0x64 fp=0xc8200479e8 sp=0xc820047960
github.com/elastic/beats/libbeat/outputs/console.(*console).PublishEvent(0xc82001007a, 0x0, 0x0, 0x0, 0xc820076210, 0x0, 0x0)
    /root/gopath/src/github.com/elastic/beats/libbeat/outputs/console/console.go:60 +0xc2 fp=0xc820047af0 sp=0xc8200479e8
github.com/elastic/beats/libbeat/outputs.(*bulkOutputAdapter).BulkPublish(0xc820010340, 0x0, 0x0, 0x0, 0xc8202d8000, 0x7, 0x800, 0x0, 0x0)
    /root/gopath/src/github.com/elastic/beats/libbeat/outputs/outputs.go:109 +0x140 fp=0xc820047bc0 sp=0xc820047af0
github.com/elastic/beats/libbeat/publisher.(*outputWorker).sendBulk(0xc8202f2140, 0xc820047d40, 0xc8202d8000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/output.go:110 +0x190 fp=0xc820047c78 sp=0xc820047bc0
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onBulk(0xc8202f2140, 0xc820047d40, 0xc8202d8000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/output.go:86 +0x39d fp=0xc820047d08 sp=0xc820047c78
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onMessage(0xc8202f2140, 0xffffffffffff0000, 0x0, 0x0, 0x0, 0xc8202d8000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/output.go:69 +0x79 fp=0xc820047d38 sp=0xc820047d08
github.com/elastic/beats/libbeat/publisher.(*messageWorker).onEvent(0xc8202f2140, 0xc8202f0000, 0x0, 0x0, 0x0, 0xc8202d8000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/worker.go:74 +0xb2 fp=0xc820047d90 sp=0xc820047d38
github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc8202f2140)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/worker.go:60 +0x34c fp=0xc820047f98 sp=0xc820047d90
runtime.goexit()
    /root/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820047fa0 sp=0xc820047f98
created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/worker.go:48 +0x126

goroutine 1 [select]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal(0xc82002a028, 0xc8202f4420, 0xc8202f4480, 0x0, 0x0)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:192 +0x412
github.com/mheese/journalbeat/beat.(*Journalbeat).Run(0xc820154000, 0xc820158000, 0x0, 0x0)
    /root/gopath/src/github.com/mheese/journalbeat/beat/journalbeat.go:248 +0xd1
github.com/elastic/beats/libbeat/beat.(*instance).run(0xc82014a100, 0x0, 0x0)
    /root/gopath/src/github.com/elastic/beats/libbeat/beat/beat.go:257 +0x120
github.com/elastic/beats/libbeat/beat.(*instance).launch(0xc82014a100, 0x1, 0x0, 0x0)
    /root/gopath/src/github.com/elastic/beats/libbeat/beat/beat.go:295 +0x1f1
github.com/elastic/beats/libbeat/beat.Run(0xa27400, 0xb, 0xa0f100, 0x5, 0x7f9ea6e571d8, 0xc820154000, 0x0, 0x0)
    /root/gopath/src/github.com/elastic/beats/libbeat/beat/beat.go:117 +0x72
main.main()
    /root/gopath/src/github.com/mheese/journalbeat/main.go:26 +0x7d

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
    /root/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
    /root/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /root/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /root/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 3 [runnable]:
github.com/elastic/beats/libbeat/outputs/logstash.(*logstash).BulkPublish(0xc82014b660, 0x0, 0x0, 0x0, 0xc8202de000, 0x7, 0x800, 0x0, 0x0)
    /root/gopath/src/github.com/elastic/beats/libbeat/outputs/logstash/logstash.go:121 +0x263
github.com/elastic/beats/libbeat/publisher.(*outputWorker).sendBulk(0xc8202f2050, 0xc82004bd40, 0xc8202de000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/output.go:110 +0x190
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onBulk(0xc8202f2050, 0xc82004bd40, 0xc8202de000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/output.go:86 +0x39d
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onMessage(0xc8202f2050, 0xffffffffffff0000, 0x0, 0x0, 0x0, 0xc8202de000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/output.go:69 +0x79
github.com/elastic/beats/libbeat/publisher.(*messageWorker).onEvent(0xc8202f2050, 0xc8202f0000, 0x0, 0x0, 0x0, 0xc8202de000, 0x7, 0x800)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/worker.go:74 +0xb2
github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc8202f2050)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/worker.go:60 +0x34c
created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/worker.go:48 +0x126

goroutine 5 [select]:
github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc820344000)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/bulk.go:60 +0x36e
created by github.com/elastic/beats/libbeat/publisher.newBulkWorker
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/bulk.go:42 +0x20d

goroutine 6 [select]:
github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc820344070)
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/bulk.go:60 +0x36e
created by github.com/elastic/beats/libbeat/publisher.newBulkWorker
    /root/gopath/src/github.com/elastic/beats/libbeat/publisher/bulk.go:42 +0x20d

goroutine 7 [select, 1 minutes, locked to thread]:
runtime.gopark(0xb1c520, 0xc820028728, 0xa17128, 0x6, 0x18, 0x2)
    /root/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820028728, 0x0, 0x18)
    /root/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820028728)
    /root/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
    /root/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
    /root/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive, 1 minutes]:
github.com/elastic/beats/libbeat/service.HandleSignals.func1(0xc8202f45a0, 0xc820010644, 0xc82000eb00)
    /root/gopath/src/github.com/elastic/beats/libbeat/service/service.go:29 +0x3a
created by github.com/elastic/beats/libbeat/service.HandleSignals
    /root/gopath/src/github.com/elastic/beats/libbeat/service/service.go:32 +0x21e

goroutine 10 [chan receive]:
github.com/mheese/journalbeat/beat.Publish(0xc820158000, 0xc820154000)
    /root/gopath/src/github.com/mheese/journalbeat/beat/journalbeat.go:262 +0x83
created by github.com/mheese/journalbeat/beat.(*Journalbeat).Run
    /root/gopath/src/github.com/mheese/journalbeat/beat/journalbeat.go:245 +0xa4

goroutine 82 [chan send, 1 minutes]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc82006c0e0, 0xc82006c070, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x91
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7

goroutine 179 [chan send]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc820344150, 0xc8203440e0, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x91
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7

goroutine 99 [chan send, 1 minutes]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc8203442a0, 0xc820344230, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x91
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7

goroutine 30 [chan send]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc820142620, 0xc8201424d0, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x91
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7

goroutine 158 [chan send]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc820142850, 0xc820142070, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x91
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7

goroutine 167 [chan send]:
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc820394230, 0xc8203941c0, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x91
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7

goroutine 177 [syscall, locked to thread]:
github.com/mheese/go-systemd/sdjournal._Cfunc_sd_journal_wait(0x7f9e8c0008c0, 0x16499e, 0x0)
    github.com/mheese/go-systemd/sdjournal/_obj/_cgo_gotypes.go:490 +0x41
github.com/mheese/go-systemd/sdjournal.(*Journal).Wait(0xc820010620, 0x5f5e100, 0xc8203945b0)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/journal.go:590 +0xd2
github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal.func1(0xc8203945b0, 0xc820394540, 0xc82002a028)
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:187 +0x63
created by github.com/mheese/go-systemd/sdjournal.(*JournalReader).FollowJournal
    /root/gopath/src/github.com/mheese/go-systemd/sdjournal/read.go:190 +0x1c7
```

System compiled on:

```
CentOS Linux release 7.2.1511 (Core)
go version go1.6.1 linux/amd64
```

**Comment by mheese** [comment]
@dwerder thanks for reporting! I've actually seen something similar with execbeat last week, and it also involved the console output. Everything was fine when I just directly moved everything to logstash, but it failed when using the console output. At the time I thought it was a problem with execbeat, but maybe it is a general libbeat issue. If you could also try to reproduce this with a different beat, that would be nice and would give us a place where to start to look.

**Comment by nicorevin** [comment]
I've tested this case recently. Seems to have been fixed in `libbeat` stable.

**Comment by mheese** [comment]
thanks @nicorevin, that's what I thought. I'm going to close this now. @dwerder please feel free to reopen this if our assumption is wrong.
